# Sequence Embedding

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

In [2]:
sequence = "ATACGATTATGACC"
sequence_split = [x for x in sequence]
#Create the vectorization layer
sequence_split


['A', 'T', 'A', 'C', 'G', 'A', 'T', 'T', 'A', 'T', 'G', 'A', 'C', 'C']

In [28]:
vectorize_layer = TextVectorization(max_tokens=10, output_mode='int', output_sequence_length=10)
vectorize_layer.adapt(sequence_split)

In [29]:
S = "ATACGAT"
V = "ATTACASDREREWE"
S_split = ' '.join(S)
V_split = ' '.join(V)
text = [S_split,V_split]
inp = vectorize_layer(text)

In [30]:
inp

<tf.Tensor: shape=(2, 10), dtype=int64, numpy=
array([[2, 3, 2, 4, 5, 2, 3, 0, 0, 0],
       [2, 3, 3, 2, 4, 2, 1, 1, 1, 1]])>

# Embedding

In [31]:
Ebd = tf.keras.layers.Embedding(input_dim=100, output_dim=2)
output = Ebd(inp)
print(output)

tf.Tensor(
[[[-0.04249822 -0.00324083]
  [-0.04824536 -0.02380964]
  [-0.04249822 -0.00324083]
  [ 0.02518258  0.01238324]
  [ 0.02435977  0.02923867]
  [-0.04249822 -0.00324083]
  [-0.04824536 -0.02380964]
  [ 0.03557335 -0.03903788]
  [ 0.03557335 -0.03903788]
  [ 0.03557335 -0.03903788]]

 [[-0.04249822 -0.00324083]
  [-0.04824536 -0.02380964]
  [-0.04824536 -0.02380964]
  [-0.04249822 -0.00324083]
  [ 0.02518258  0.01238324]
  [-0.04249822 -0.00324083]
  [ 0.01306046  0.03019983]
  [ 0.01306046  0.03019983]
  [ 0.01306046  0.03019983]
  [ 0.01306046  0.03019983]]], shape=(2, 10, 2), dtype=float32)
